# Generated by Django 5.2.10 on 2026-04-09 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=20, unique=True)),
                ("nom", models.CharField(blank=True, default="", max_length=200)),
                ("pays", models.CharField(blank=True, default="", max_length=5)),
                ("secteur", models.CharField(blank=True, default="", max_length=100)),
                ("isin", models.CharField(blank=True, default="", max_length=20)),
                ("description", models.TextField(blank=True, default="")),
                ("nombre_actions", models.BigIntegerField(blank=True, null=True)),
                ("flottant_pct", models.FloatField(blank=True, null=True)),
                ("chiffre_affaires", models.FloatField(blank=True, null=True)),
                ("resultat_net", models.FloatField(blank=True, null=True)),
                ("bnpa", models.FloatField(blank=True, null=True)),
                ("per", models.FloatField(blank=True, null=True)),
                ("dividende", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Action",
                "verbose_name_plural": "Actions",
                "ordering": ["ticker"],
            },
        ),
        migrations.CreateModel(
            name="Indice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=30, unique=True)),
                ("nom", models.CharField(blank=True, default="", max_length=200)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Indice",
                "verbose_name_plural": "Indices",
                "ordering": ["ticker"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_source", models.IntegerField(db_index=True, unique=True)),
                ("titre", models.CharField(max_length=500)),
                (
                    "date_publication",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("auteur", models.CharField(blank=True, default="", max_length=200)),
                ("categorie", models.CharField(blank=True, default="", max_length=200)),
                ("contenu", models.TextField(blank=True, default="")),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                ("url", models.URLField(blank=True, default="", max_length=500)),
            ],
            options={
                "verbose_name": "Actualité",
                "verbose_name_plural": "Actualités",
                "ordering": ["-date_publication"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_scraping", models.CharField(max_length=50)),
                ("date_debut", models.DateTimeField(auto_now_add=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("statut", models.CharField(default="en_cours", max_length=20)),
                ("message", models.TextField(blank=True, default="")),
                ("nb_elements", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Log de Scraping",
                "verbose_name_plural": "Logs de Scraping",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("ouverture", models.FloatField(blank=True, null=True)),
                ("plus_haut", models.FloatField(blank=True, null=True)),
                ("plus_bas", models.FloatField(blank=True, null=True)),
                ("cloture", models.FloatField(blank=True, null=True)),
                ("volume_titres", models.BigIntegerField(blank=True, null=True)),
                ("volume_fcfa", models.FloatField(blank=True, null=True)),
                ("variation_pct", models.FloatField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Action",
                "verbose_name_plural": "Historiques Actions",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["action", "date"], name="dashboard_h_action__e7234f_idx"
                    )
                ],
                "unique_together": {("action", "date")},
            },
        ),
        migrations.CreateModel(
            name="HistoriqueIndice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("ouverture", models.FloatField(blank=True, null=True)),
                ("plus_haut", models.FloatField(blank=True, null=True)),
                ("plus_bas", models.FloatField(blank=True, null=True)),
                ("cloture", models.FloatField(blank=True, null=True)),
                ("volume_titres", models.BigIntegerField(blank=True, null=True)),
                ("volume_fcfa", models.FloatField(blank=True, null=True)),
                ("variation_pct", models.FloatField(blank=True, null=True)),
                (
                    "indice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques",
                        to="dashboard.indice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Indice",
                "verbose_name_plural": "Historiques Indices",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["indice", "date"], name="dashboard_h_indice__0dc82c_idx"
                    )
                ],
                "unique_together": {("indice", "date")},
            },
        ),
    ]
