# Generated by Django 5.2.10 on 2026-04-09 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle", models.CharField(max_length=50, unique=True)),
                ("valeur", models.CharField(max_length=500)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration API",
                "verbose_name_plural": "Configurations API",
            },
        ),
        migrations.CreateModel(
            name="CommentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analyse", models.TextField(verbose_name="Commentaire d'analyse")),
                ("recommandation", models.TextField(verbose_name="Recommandation")),
                ("disclaimer", models.TextField(blank=True, default="")),
                (
                    "donnees_contexte",
                    models.JSONField(default=dict, verbose_name="Données de contexte"),
                ),
                (
                    "modele_ia",
                    models.CharField(
                        default="claude-sonnet-4-20250514", max_length=100
                    ),
                ),
                ("favori", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique commentaire",
                "verbose_name_plural": "Historique commentaires",
                "ordering": ["-date_creation"],
            },
        ),
    ]
