# Generated by Django 5.2.10 on 2026-04-10 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_apiconfig_commenthistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_generation",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "periode_analyse",
                    models.CharField(
                        default="1y", max_length=10, verbose_name="Période d'analyse"
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        choices=[
                            ("ACHAT", "Achat"),
                            ("VENTE", "Vente"),
                            ("NEUTRE", "Neutre"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "confiance",
                    models.FloatField(verbose_name="Niveau de confiance (%)"),
                ),
                (
                    "prix_entree",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Prix d'entrée"
                    ),
                ),
                ("stop_loss", models.FloatField(blank=True, null=True)),
                ("take_profit", models.FloatField(blank=True, null=True)),
                (
                    "risk_reward",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ratio Risque/Rendement"
                    ),
                ),
                (
                    "supports",
                    models.JSONField(default=list, verbose_name="Niveaux de support"),
                ),
                (
                    "resistances",
                    models.JSONField(
                        default=list, verbose_name="Niveaux de résistance"
                    ),
                ),
                (
                    "justification",
                    models.TextField(verbose_name="Justification technique"),
                ),
                (
                    "indicateurs_utilises",
                    models.JSONField(default=list, verbose_name="Indicateurs utilisés"),
                ),
                (
                    "valeurs_indicateurs",
                    models.JSONField(
                        default=dict, verbose_name="Valeurs des indicateurs"
                    ),
                ),
                ("modele_ia", models.CharField(default="sonnet", max_length=50)),
                (
                    "prix_actuel",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Prix au moment du signal"
                    ),
                ),
                ("favori", models.BooleanField(default=False)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signaux",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signal de trading",
                "verbose_name_plural": "Signaux de trading",
                "ordering": ["-date_generation"],
                "indexes": [
                    models.Index(
                        fields=["action", "-date_generation"],
                        name="dashboard_t_action__5f06b5_idx",
                    )
                ],
            },
        ),
    ]
