# Generated by Django 5.2.10 on 2026-04-11 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_add_trading_signal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portefeuille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "montant_initial",
                    models.FloatField(verbose_name="Montant alloué (FCFA)"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "frais_courtage_pct",
                    models.FloatField(
                        default=1.0, verbose_name="Frais de courtage (%)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Portefeuille",
                "verbose_name_plural": "Portefeuilles",
                "ordering": ["-date_modification"],
            },
        ),
        migrations.CreateModel(
            name="LignePortefeuille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField(verbose_name="Nombre de titres")),
                (
                    "prix_achat",
                    models.FloatField(verbose_name="Prix d'achat unitaire (FCFA)"),
                ),
                ("date_achat", models.DateField(verbose_name="Date d'achat")),
                (
                    "frais",
                    models.FloatField(
                        default=0, verbose_name="Frais de transaction (FCFA)"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.action",
                    ),
                ),
                (
                    "portefeuille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="dashboard.portefeuille",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de portefeuille",
                "verbose_name_plural": "Lignes de portefeuille",
                "ordering": ["-date_creation"],
            },
        ),
    ]
