# Generated by Django 5.2.10 on 2026-04-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_portefeuille_ligneportefeuille"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("scraper_actions", "Scraper Actions/Indices"),
                            ("scraper_news", "Scraper News"),
                            ("analyse", "Analyse Technique"),
                            ("signaux", "Signaux IA"),
                            ("alertes", "Alertes Marché"),
                            ("health", "Santé Application"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("actif", models.BooleanField(default=True)),
                (
                    "cron_expression",
                    models.CharField(help_text="Ex: 0 7 * * 1-5", max_length=50),
                ),
                ("timeout_seconds", models.IntegerField(default=300)),
                ("config_json", models.JSONField(blank=True, default=dict)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuration Agent",
                "verbose_name_plural": "Configurations Agents",
                "ordering": ["agent_type"],
            },
        ),
        migrations.CreateModel(
            name="AgentAlerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Avertissement"),
                            ("danger", "Critique"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("lue", models.BooleanField(default=False)),
                ("donnees_json", models.JSONField(blank=True, default=dict)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes",
                        to="dashboard.agentconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte Agent",
                "verbose_name_plural": "Alertes Agents",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AgentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("succes", "Succès"),
                            ("erreur", "Erreur"),
                            ("timeout", "Timeout"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateTimeField(blank=True, null=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("duree_seconds", models.FloatField(blank=True, null=True)),
                ("declencheur", models.CharField(default="scheduler", max_length=50)),
                ("resultat_json", models.JSONField(blank=True, default=dict)),
                ("message", models.TextField(blank=True, default="")),
                ("nb_elements_traites", models.IntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taches",
                        to="dashboard.agentconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche Agent",
                "verbose_name_plural": "Tâches Agents",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="AgentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("details_json", models.JSONField(blank=True, default=dict)),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="dashboard.agentconfig",
                    ),
                ),
                (
                    "tache",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="dashboard.agenttask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Agent",
                "verbose_name_plural": "Logs Agents",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AgentDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obligatoire", models.BooleanField(default=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependances",
                        to="dashboard.agentconfig",
                    ),
                ),
                (
                    "depends_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependants",
                        to="dashboard.agentconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépendance Agent",
                "verbose_name_plural": "Dépendances Agents",
                "unique_together": {("agent", "depends_on")},
            },
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(
                fields=["agent", "-date_debut"], name="dashboard_a_agent_i_8c8db0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(fields=["statut"], name="dashboard_a_statut_40b5c0_idx"),
        ),
        migrations.AddIndex(
            model_name="agentlog",
            index=models.Index(
                fields=["agent", "-date"], name="dashboard_a_agent_i_f16ca4_idx"
            ),
        ),
    ]
