# Generated by Django 5.2.10 on 2026-04-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_agentconfig_agentalerte_agenttask_agentlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicateurCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_calcul", models.DateTimeField(auto_now=True, db_index=True)),
                ("indicateurs_json", models.JSONField(default=dict)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicateurs_cache",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache Indicateur",
                "verbose_name_plural": "Cache Indicateurs",
                "unique_together": {("action",)},
            },
        ),
        migrations.CreateModel(
            name="SignalChangement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ancien_signal", models.CharField(max_length=10)),
                ("nouveau_signal", models.CharField(max_length=10)),
                ("ancien_confiance", models.FloatField(blank=True, null=True)),
                ("nouveau_confiance", models.FloatField(blank=True, null=True)),
                ("justification", models.TextField(blank=True, default="")),
                ("date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changements_signal",
                        to="dashboard.action",
                    ),
                ),
                (
                    "signal_nouveau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dashboard.tradingsignal",
                    ),
                ),
                (
                    "signal_precedent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="dashboard.tradingsignal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Changement de Signal",
                "verbose_name_plural": "Changements de Signaux",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["action", "-date"],
                        name="dashboard_s_action__dfb9b2_idx",
                    )
                ],
            },
        ),
    ]
