# Generated by Django 5.2.10 on 2026-05-15 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_indicateurcache_signalchangement"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationStrategie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "strategie",
                    models.CharField(
                        choices=[
                            ("SHARPE_HMM", "Sharpe HMM"),
                            ("DYN_HMM", "Dynamic HMM"),
                            ("MR_HMM", "Max Return HMM"),
                            ("RP_HMM", "Risk Parity HMM"),
                            ("MD_HMM", "Max Diversification HMM"),
                            ("MV_HMM", "Min Variance HMM"),
                        ],
                        default="SHARPE_HMM",
                        max_length=20,
                    ),
                ),
                ("poids_facteurs", models.JSONField(help_text="Dict {facteur: poids}")),
                ("poids_actions", models.JSONField(help_text="Dict {ticker: poids}")),
                ("nb_actions_top", models.IntegerField(default=15)),
                (
                    "methode_normalisation",
                    models.CharField(default="zscore", max_length=20),
                ),
                (
                    "declencheur",
                    models.CharField(default="regime_change", max_length=50),
                ),
                ("rendement_attendu", models.FloatField(blank=True, null=True)),
                ("volatilite_attendue", models.FloatField(blank=True, null=True)),
                ("sharpe_attendu", models.FloatField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Allocation Stratégie",
                "verbose_name_plural": "Allocations Stratégie",
                "ordering": ["-date", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ParametresHMM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_entrainement", models.DateField(db_index=True, unique=True)),
                ("n_observations", models.IntegerField()),
                ("n_regimes", models.IntegerField(default=2)),
                ("n_facteurs", models.IntegerField(default=13)),
                ("matrice_transition", models.JSONField()),
                ("moyennes_regime_0", models.JSONField()),
                ("moyennes_regime_1", models.JSONField()),
                ("covariance_regime_0", models.JSONField()),
                ("covariance_regime_1", models.JSONField()),
                ("log_likelihood", models.FloatField()),
                ("converged", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Paramètres HMM",
                "verbose_name_plural": "Paramètres HMM",
                "ordering": ["-date_entrainement"],
            },
        ),
        migrations.CreateModel(
            name="RegimeMarche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "regime_brut",
                    models.IntegerField(help_text="Régime brut prédit (0 ou 1)"),
                ),
                (
                    "regime_confirme",
                    models.IntegerField(
                        help_text="Régime confirmé après filtre de stabilité (d=5 jours)"
                    ),
                ),
                ("proba_regime_0", models.FloatField(default=0.0)),
                ("proba_regime_1", models.FloatField(default=0.0)),
                ("changement", models.BooleanField(default=False)),
                ("declenche_reallocation", models.BooleanField(default=False)),
                ("log_likelihood", models.FloatField(blank=True, null=True)),
                ("date_calcul", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Régime de Marché",
                "verbose_name_plural": "Régimes de Marché",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PortefeuilleStrategie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("strategie", models.CharField(default="SHARPE_HMM", max_length=20)),
                ("capital_initial", models.FloatField()),
                ("capital_courant", models.FloatField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
                ("frais_courtage_pct", models.FloatField(default=0.01)),
                (
                    "derniere_allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portefeuilles",
                        to="dashboard.allocationstrategie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portefeuille Stratégie",
                "verbose_name_plural": "Portefeuilles Stratégie",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="OrdreReallocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_ordre",
                    models.CharField(
                        choices=[
                            ("ACHAT", "Achat"),
                            ("VENTE", "Vente"),
                            ("CONSERVER", "Conserver"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantite", models.IntegerField()),
                ("prix_indicatif", models.FloatField()),
                ("montant_estime", models.FloatField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("EXECUTE", "Exécuté"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=15,
                    ),
                ),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                ("date_execution", models.DateTimeField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.action",
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.allocationstrategie",
                    ),
                ),
                (
                    "portefeuille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordres",
                        to="dashboard.portefeuillestrategie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordre de Réallocation",
                "verbose_name_plural": "Ordres de Réallocation",
                "ordering": ["-date_generation"],
            },
        ),
        migrations.CreateModel(
            name="PositionStrategie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                ("prix_achat_moyen", models.FloatField()),
                ("poids_cible", models.FloatField()),
                ("poids_effectif", models.FloatField(default=0.0)),
                ("date_entree", models.DateField()),
                ("active", models.BooleanField(default=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.action",
                    ),
                ),
                (
                    "portefeuille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="dashboard.portefeuillestrategie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position Stratégie",
                "verbose_name_plural": "Positions Stratégie",
                "ordering": ["-poids_cible"],
            },
        ),
        migrations.AddField(
            model_name="allocationstrategie",
            name="regime",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.regimemarche",
            ),
        ),
        migrations.CreateModel(
            name="RendementPortefeuilleFactoriel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facteur", models.CharField(db_index=True, max_length=20)),
                ("date", models.DateField(db_index=True)),
                ("rendement", models.FloatField()),
            ],
            options={
                "verbose_name": "Rendement Portefeuille Factoriel",
                "verbose_name_plural": "Rendements Portefeuilles Factoriels",
                "ordering": ["-date", "facteur"],
                "unique_together": {("facteur", "date")},
            },
        ),
        migrations.CreateModel(
            name="FacteurStrategie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facteur",
                    models.CharField(
                        choices=[
                            ("BtM", "Book-to-Market"),
                            ("EP", "Earnings-to-Price"),
                            ("SP", "Sales-to-Price"),
                            ("ROA", "Return on Assets"),
                            ("ROE", "Return on Equity"),
                            ("LEVIER", "Levier financier"),
                            ("DIV_YIELD", "Dividend Yield"),
                            ("VARIANCE", "Variance"),
                            ("RDT_JOURNALIER", "Rendement journalier"),
                            ("MOM_6M", "6-Month Momentum"),
                            ("VOLUME", "Volume de transaction"),
                            ("BETA", "Bêta"),
                            ("CAPI", "Capitalisation boursière"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("valeur", models.FloatField()),
                ("date_calcul", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facteurs_strategie",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facteur Stratégie",
                "verbose_name_plural": "Facteurs Stratégie",
                "ordering": ["-date", "facteur"],
                "indexes": [
                    models.Index(
                        fields=["date", "facteur"], name="dashboard_f_date_3b2119_idx"
                    )
                ],
                "unique_together": {("action", "facteur", "date")},
            },
        ),
        migrations.CreateModel(
            name="FondamentauxAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("capitaux_propres", models.FloatField(blank=True, null=True)),
                ("total_actif", models.FloatField(blank=True, null=True)),
                ("dette_totale", models.FloatField(blank=True, null=True)),
                ("chiffre_affaires", models.FloatField(blank=True, null=True)),
                ("resultat_net", models.FloatField(blank=True, null=True)),
                ("bnpa", models.FloatField(blank=True, null=True)),
                ("dividende", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(default="excel_import", max_length=50)),
                ("date_import", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fondamentaux",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fondamentaux Action",
                "verbose_name_plural": "Fondamentaux Actions",
                "ordering": ["-date"],
                "unique_together": {("action", "date")},
            },
        ),
    ]
