# Generated by Django 5.2.10 on 2026-05-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_strategie_hmm"),
    ]

    operations = [
        migrations.CreateModel(
            name="BilanActif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercice",
                    models.IntegerField(
                        db_index=True, help_text="Année de l'exercice (ex: 2024)"
                    ),
                ),
                (
                    "total_actif",
                    models.FloatField(
                        blank=True,
                        help_text="Total actif = Total passif (FCFA)",
                        null=True,
                    ),
                ),
                ("actif_courants", models.FloatField(blank=True, null=True)),
                (
                    "treso_active",
                    models.FloatField(
                        blank=True, help_text="Trésorerie active", null=True
                    ),
                ),
                ("source", models.CharField(default="excel_import", max_length=50)),
                ("date_import", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bilans_actif",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bilan – Actif",
                "verbose_name_plural": "Bilans – Actif",
                "ordering": ["-exercice", "action"],
                "unique_together": {("action", "exercice")},
            },
        ),
        migrations.CreateModel(
            name="BilanPassif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercice", models.IntegerField(db_index=True)),
                ("capitaux_propres", models.FloatField(blank=True, null=True)),
                ("total_dettes", models.FloatField(blank=True, null=True)),
                ("passif_courants", models.FloatField(blank=True, null=True)),
                (
                    "resultat_non_reparti",
                    models.FloatField(
                        blank=True, help_text="Report à nouveau", null=True
                    ),
                ),
                ("source", models.CharField(default="excel_import", max_length=50)),
                ("date_import", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bilans_passif",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bilan – Passif",
                "verbose_name_plural": "Bilans – Passif",
                "ordering": ["-exercice", "action"],
                "unique_together": {("action", "exercice")},
            },
        ),
        migrations.CreateModel(
            name="CompteResultat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercice", models.IntegerField(db_index=True)),
                ("chiffre_affaires", models.FloatField(blank=True, null=True)),
                (
                    "ebit",
                    models.FloatField(
                        blank=True, help_text="Résultat d'exploitation", null=True
                    ),
                ),
                ("resultat_net", models.FloatField(blank=True, null=True)),
                (
                    "dividende_annuel",
                    models.FloatField(
                        blank=True,
                        help_text="Dividende versé au titre de l'exercice (par action, FCFA)",
                        null=True,
                    ),
                ),
                ("source", models.CharField(default="excel_import", max_length=50)),
                ("date_import", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comptes_resultat",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte de Résultat",
                "verbose_name_plural": "Comptes de Résultat",
                "ordering": ["-exercice", "action"],
                "unique_together": {("action", "exercice")},
            },
        ),
        migrations.CreateModel(
            name="FluxTresorerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercice", models.IntegerField(db_index=True)),
                (
                    "cfo",
                    models.FloatField(
                        blank=True, help_text="Cash-flow opérationnel", null=True
                    ),
                ),
                (
                    "capex",
                    models.FloatField(
                        blank=True, help_text="Capex (souvent négatif)", null=True
                    ),
                ),
                ("fcf_operationnel", models.FloatField(blank=True, null=True)),
                ("fcf_treso_disponible", models.FloatField(blank=True, null=True)),
                ("source", models.CharField(default="excel_import", max_length=50)),
                ("date_import", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flux_tresorerie",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flux de Trésorerie",
                "verbose_name_plural": "Flux de Trésorerie",
                "ordering": ["-exercice", "action"],
                "unique_together": {("action", "exercice")},
            },
        ),
        migrations.DeleteModel(
            name="FondamentauxAction",
        ),
    ]
