# Generated by Django 5.2.10 on 2026-05-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_remove_agent_monitoring"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationstrategie",
            name="capital_reference",
            field=models.FloatField(
                blank=True,
                help_text="Capital de référence en FCFA utilisé pour le calcul des contraintes ADV",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocationstrategie",
            name="contraintes_liquidite",
            field=models.JSONField(
                blank=True,
                help_text="Dict {ticker: {adv, w_max, poids_brut, poids_contraint, feasible}}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocationstrategie",
            name="lambda_participation",
            field=models.FloatField(
                default=0.15,
                help_text="Taux de participation max (fraction du volume journalier, ex: 0.15 = 15%)",
            ),
        ),
    ]
