# Generated by Django 5.2.10 on 2026-05-22 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_allocation_liquidite"),
    ]

    operations = [
        migrations.CreateModel(
            name="FondamentauxAnnuel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercice",
                    models.IntegerField(
                        db_index=True, help_text="Année de l'exercice (ex: 2024)"
                    ),
                ),
                (
                    "chiffre_affaires",
                    models.FloatField(
                        blank=True, help_text="CA en millions FCFA", null=True
                    ),
                ),
                (
                    "croissance_ca",
                    models.FloatField(
                        blank=True, help_text="Croissance CA en %", null=True
                    ),
                ),
                (
                    "resultat_net",
                    models.FloatField(
                        blank=True, help_text="RN en millions FCFA", null=True
                    ),
                ),
                (
                    "croissance_rn",
                    models.FloatField(
                        blank=True, help_text="Croissance RN en %", null=True
                    ),
                ),
                (
                    "bnpa",
                    models.FloatField(
                        blank=True,
                        help_text="Bénéfice net par action (FCFA)",
                        null=True,
                    ),
                ),
                (
                    "per",
                    models.FloatField(
                        blank=True, help_text="Price Earning Ratio", null=True
                    ),
                ),
                (
                    "dividende",
                    models.FloatField(
                        blank=True, help_text="Dividende par action (FCFA)", null=True
                    ),
                ),
                ("source", models.CharField(default="sikafinance", max_length=50)),
                ("source_url", models.URLField(blank=True, default="")),
                ("date_import", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fondamentaux_annuels",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fondamental Annuel (scrap)",
                "verbose_name_plural": "Fondamentaux Annuels (scrap)",
                "ordering": ["action", "-exercice"],
                "indexes": [
                    models.Index(
                        fields=["action", "-exercice"],
                        name="dashboard_f_action__2cd2f8_idx",
                    )
                ],
                "unique_together": {("action", "exercice")},
            },
        ),
    ]
