# Generated by Django 5.2.10 on 2026-05-22 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_conseilsikafinance"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("GARCH", "GARCH(1,1)"),
                            ("GJR-GARCH", "GJR-GARCH(1,1,1)"),
                            ("EGARCH", "EGARCH(1,1)"),
                            ("INSUFFISANT", "Observations insuffisantes"),
                            ("FAILED", "Échec d'estimation"),
                        ],
                        max_length=15,
                    ),
                ),
                ("p", models.IntegerField(blank=True, null=True)),
                ("q", models.IntegerField(blank=True, null=True)),
                (
                    "o",
                    models.IntegerField(
                        blank=True, help_text="Asymétrie (GJR/EGARCH)", null=True
                    ),
                ),
                ("omega", models.FloatField(blank=True, null=True)),
                ("alpha", models.FloatField(blank=True, null=True)),
                ("beta", models.FloatField(blank=True, null=True)),
                (
                    "gamma",
                    models.FloatField(
                        blank=True, help_text="Effet de levier", null=True
                    ),
                ),
                (
                    "persistence",
                    models.FloatField(
                        blank=True, help_text="α+β (ou équivalent)", null=True
                    ),
                ),
                ("aic", models.FloatField(blank=True, null=True)),
                ("bic", models.FloatField(blank=True, null=True)),
                (
                    "llf",
                    models.FloatField(
                        blank=True, help_text="Log-likelihood", null=True
                    ),
                ),
                ("n_obs", models.IntegerField(blank=True, null=True)),
                (
                    "vol_actuelle_annualisee",
                    models.FloatField(
                        blank=True, help_text="σ_T × √252 (en %)", null=True
                    ),
                ),
                (
                    "vol_conditionnelle_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Série des 252 derniers σ_t quotidiens",
                    ),
                ),
                ("fitted_date", models.DateTimeField(auto_now=True)),
                (
                    "erreur_message",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garch_model",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle GARCH",
                "verbose_name_plural": "Modèles GARCH",
                "ordering": ["action"],
            },
        ),
    ]
