# Generated by Django 5.2.10 on 2026-05-22 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_garchmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("code", models.CharField(db_index=True, max_length=12)),
                ("label", models.CharField(blank=True, default="", max_length=20)),
                ("score", models.FloatField(blank=True, null=True)),
                ("n_axes_valides", models.IntegerField(default=0)),
                ("axes_detail_json", models.JSONField(blank=True, default=dict)),
                ("date_calcul", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signaux_historiques",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signal Historique",
                "verbose_name_plural": "Signaux Historiques",
                "ordering": ["action", "-date"],
                "indexes": [
                    models.Index(
                        fields=["action", "-date"],
                        name="dashboard_s_action__870b12_idx",
                    ),
                    models.Index(
                        fields=["code", "-date"], name="dashboard_s_code_a07d9f_idx"
                    ),
                ],
                "unique_together": {("action", "date")},
            },
        ),
    ]
