# Generated by Django 5.2.10 on 2026-05-23 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_signalhistorique"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarchFitHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fin_de_periode",
                    models.DateField(
                        db_index=True,
                        help_text="Dernière date incluse dans la fenêtre de calibration",
                    ),
                ),
                ("model_type", models.CharField(max_length=15)),
                ("omega", models.FloatField(blank=True, null=True)),
                ("alpha", models.FloatField(blank=True, null=True)),
                ("beta", models.FloatField(blank=True, null=True)),
                ("gamma", models.FloatField(blank=True, null=True)),
                (
                    "sigma_T_pct_quotidien",
                    models.FloatField(
                        blank=True,
                        help_text="σ_T en % quotidien à la fin de la fenêtre",
                        null=True,
                    ),
                ),
                ("n_obs", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garch_fits",
                        to="dashboard.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache GARCH (fenêtre)",
                "verbose_name_plural": "Cache GARCH (fenêtres)",
                "ordering": ["action", "fin_de_periode"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("action", "fin_de_periode"),
                        name="uniq_garchfit_action_fin",
                    )
                ],
            },
        ),
    ]
